packages:
  # Core
  - 'packages/core'
  - 'packages/runtime'
  - 'packages/testing'
  # AI
  - 'packages/ai/providers/*'
  # Providers 
  - 'packages/providers/di/*'
  - 'packages/providers/validation/*'
  - 'packages/providers/configuration/*'
