packages:
  - 'packages/core'
  - 'packages/runtime'
  - 'packages/testing'
  - 'packages/cli'
  - 'packages/plugins/ai/*'
  - 'packages/plugins/database/*'
  - 'packages/plugins/http/*'
  - 'packages/plugins/messaging/*'
  - 'packages/plugins/di/*'
  - 'packages/plugins/observability/*'
  - 'packages/plugins/utilities/*'
  - 'docs/website'
